### ISSUE TITLE
0-th value returned by pyfunc_0 is int, but expects float

### ISSUE THREAD

**Issue by Eldart95** [Trustworthy-Software/DexRay#1]
Hello, when trying to run dexray.py with datasets generated with provided hashes, i'm getting the error:
0-th value returned by pyfunc_0 is int, but expects float

any ideas why and how to solve it ?
thanks

**Comment by DaoudiNadia** [comment]
Hi, do you have a link to an image sample from the dataset you generated?

**Comment by Eldart95** [comment]
Thanks for the reply, i posted the wrong error ,sorry about that ,will edit.

**Comment by Eldart95** [comment]
changing line 53 from "int64" to "int32" fixed the issue.
